name: CI-PR

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name actions
          git config user.email doralteres@gmail.com
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: pnpm i
      - run: pnpm run lint
      - run: pnpm run test --coverage
      - name: 'Report Coverage'
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
