name: CI-Main

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.github/**'
      - 'example/**'
      - 'pnpm-lock.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name actions
          git config user.email doralteres@gmail.com
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true
      - run: pnpm run test --coverage

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config user.name actions
          git config user.email doralteres@gmail.com
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node
      - uses: pnpm/action-setup@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          version: 8
          run_install: true
      - run: git status
        if: ${{ steps.release.outputs.release_created }}
      - run: pnpm publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
