name: CI-Main

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name actions
          git config user.email doralteres@gmail.com
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: yarn
      - run: yarn lint

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config user.name actions
          git config user.email doralteres@gmail.com
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn release
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'package.json'
          prop_path: 'version'
      - name: Push Release tag
        run: git push --follow-tags origin main
      - name: Create Release Changelog
        run: npx extract-changelog-release > RELEASE_BODY.md
      - uses: ncipollo/release-action@v1
        with:
          bodyFile: 'RELEASE_BODY.md'
          tag: v${{steps.version.outputs.prop}}
